name: check-links
on:
  workflow_dispatch:
  schedule:
    - cron: '37 8 * * *'
  push:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: filiph/linkcheck@3.0.0
        with:
          arguments: -e https://yftdtddh.github.io/muxizyhz/
