name: check-links
on:
  workflow_dispatch:
  schedule:
    - cron: '37 8 * * *'
  push:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.
    - name: Run URL check script
      uses: adriancoman/link-checks-action@0.1.0
      with:
        file-to-check: "index.html"
